### ISSUE TITLE
Fails to build running XCode < 7

### ISSUE THREAD

**Issue by brock** [thomascullen/voicebox#10]
I'm going to investigate this myself, but I'm adding this here in case other folks come across it. I'm sure I'll be able to figure it out, and will post a solution shortly. (_directories have been normalized_)

```
$ npm install
> nslog@3.0.0 install ./node_modules/electron-rebuild/node_modules/nslog
> node-gyp rebuild

make: Entering directory './node_modules/electron-rebuild/node_modules/nslog/build'
  CXX(target) Release/obj.target/nslog/src/main.o
  CXX(target) Release/obj.target/nslog/src/nslog_mac.o
  SOLINK_MODULE(target) Release/nslog.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
nslog.target.mk:162: recipe for target 'Release/nslog.node' failed
make: *** [Release/nslog.node] Error 1
make: Leaving directory './node_modules/electron-rebuild/node_modules/nslog/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (~/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "~/.nvm/versions/node/v4.0.0/bin/node" "~/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ./node_modules/electron-rebuild/node_modules/nslog
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok

> electron-prebuilt@0.33.1 postinstall ./node_modules/electron-prebuilt
> node install.js

Downloading electron-v0.33.1-darwin-x64.zip
[============================================>] 100.0% of 37.86 MB (5.61 MB/s)
npm ERR! Darwin 14.5.0
npm ERR! argv "~/.nvm/versions/node/v4.0.0/bin/node" "~/.nvm/versions/node/v4.0.0/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ./npm-debug.log
```

**Comment by brock** [comment]
Upgrading XCode as was documented here https://github.com/Homebrew/homebrew/issues/40653

**Comment by brock** [comment]
Working after I upgraded to XCode 7
